# Generated by Django 4.1 on 2022-08-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='trending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
